### ISSUE TITLE
Alignment of portfolio items when additional items are added

### ISSUE THREAD

**Issue by davidtmiller** [StartBootstrap/startbootstrap-freelancer#270]
There should be a `.justify-content-center` utility on the parent row for the portfolio items so they center when more are added and there is an odd number of items showing.

**Comment by jovis9611** [comment]
Hi, i have problem with responsive design. If i add a new div under about section and make some modification in css to replace the top as video clip. The problem occured is it because of  css or have to make changes on div col-md-x?

**Comment by davidtmiller** [comment]
I would have to see an example of what you're referencing. There should be a pretty simple resolution using some Bootstrap layout classes though!

**Comment by davidtmiller** [comment]
I just realized I answered my own issue...
