### ISSUE TITLE
Riddled with Content-Security-Policy errors

### ISSUE THREAD

**Issue by Marcioshub** [StartBootstrap/startbootstrap-freelancer#286]
It won't even show anything...
![image](https://user-images.githubusercontent.com/1448245/94389520-0df8fc00-011e-11eb-8fbb-789358f79797.png)

**Comment by davidtmiller** [comment]
None of these errors are appearing on the live demo here https://startbootstrap.github.io/startbootstrap-freelancer/ - something is blocking the use of the CDN's on your browser it seems.
