### ISSUE TITLE
 ### INFO: Rendering src\pug\index.pug to src\pug\index.html - Is this correct?

### ISSUE THREAD

**Issue by carloswm85** [StartBootstrap/startbootstrap-freelancer#295]
I'm running the command `npm start debug`, and when changing the .pug file, the output file is sent to that folder. I've tried to fix the JS files myself, unsuccessfully.  I suspect the problem is somewhere on: `_renderAllPug()`

First time render works. The watched renders doesn't.

**Comment by davidtmiller** [comment]
This should be fixed now as of using upath within the Pug render.
