### ISSUE TITLE
Add Dark mode

### ISSUE THREAD

**Issue by chnuessli** [StartBootstrap/startbootstrap-freelancer#296]
Wouldn't it be nice to have a dark mode option?
I think i will give it a try, but definitely need a little bit of css help here. Anyone wants to join?

**Comment by chnuessli** [comment]
I've created a dark theme for this starter: https://github.com/chnuessli/startbootstrap-freelancer-dark
Can someone help me with the button to toggle dark mode?

**Comment by davidtmiller** [comment]
This is certainly a cool feature, but not something that we will include with the base theme at this time. Thanks for the link though, and hopefully some folks get some use out of this technique!
