### ISSUE TITLE
Is there a way to turn a modal's pop up page into it's own page on the website?

### ISSUE THREAD

**Issue by aoztanir** [StartBootstrap/startbootstrap-freelancer#298]
Im trying to make it that I can give someone the link to a specific portfolio item, and they will be able to use the link to access it, if there is an easy way to turn a modal into a page then that would be great, but even easier is there an easy way to link a modal, so if I typed my site /portfolio item name it would route to the modal?

Thnaks,
Aryah

**Comment by davidtmiller** [comment]
Simply replace the link with a URL rather than the modal ID and it will link out to a separate page. Hopefully this helps!
