### ISSUE TITLE
index.html resetting when running npm start

### ISSUE THREAD

**Issue by timmshinbone** [StartBootstrap/startbootstrap-freelancer#308]
A friend of mine is using this template and I've been trying to help him out, but we're both stuck. Basically, running `npm start` is replacing all of the changed files in `dist/` with the files in `src/`, I get that this is how the template compiles them when it runs the `clean` script, but it's completely replacing the index.html code with the template code in `index.pug` and all of the changes are overwritten in the text editor, even the added image files are removed. 

Do we have to update the index.pug file at all or update the scripts? We really can't figure this out since the template's readme just says to add code in the index.html. Are we missing a step somewhere?

**Comment by davidtmiller** [comment]
If you're not using the source files for development, you don't need to be running and of the npm scripts. You could take the `dist` directory and use those as-is if you'd just like to work with HTML/CSS, but if you want to work with SASS and Pug, modify the files in `src` and then run the `npm start` scripts.

When the script is run, the HTML is built from the Pug, so the `index.pug` is replacing whatever is in the `index.html` file in the `dist` directory. Hopefully this helps!
